server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Host log dosyaları
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/log/*log

  # Docker container stdout/stderr logları
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'

  # Backend uygulama log dosyaları
  - job_name: backend-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend-app
          service: trading-bot
          __path__: /app/logs/app.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            logger: logger
            event: event
            timestamp: timestamp
            extra: extra
            checks: checks
            error: error
      - json:
          source: checks
          expressions:
            database_status: database
            redis_status: redis
            twitter_api_status: twitter_api
            binance_api_status: binance_api
      - labels:
          level:
          logger:
          service:
          database_status:
          redis_status:
          twitter_api_status:
          binance_api_status:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: event

  # Syslog (opsiyonel)
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
