"""Initial migration: create tweets, trades, and positions tables

Revision ID: 604e84bb206d
Revises: 
Create Date: 2025-08-31 15:30:22.351982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604e84bb206d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_entry', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=True)
    op.create_table('tweets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('signal_score', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at_db', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweets_author'), 'tweets', ['author'], unique=False)
    op.create_index(op.f('ix_tweets_created_at'), 'tweets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tweets_id'), 'tweets', ['id'], unique=False)
    op.create_index(op.f('ix_tweets_processed'), 'tweets', ['processed'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_tweet_id'), 'trades', ['tweet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_tweet_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_tweets_processed'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_id'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_created_at'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_author'), table_name='tweets')
    op.drop_table('tweets')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
